version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '0 0 1 1,4,7,10 *'
    cooldown:
      default-days: 7
    allow:
      - dependency-type: 'all'
    commit-message:
      prefix: 'build'
      include: 'scope'
