import { promises as fs } from "node:fs";
import path from "node:path";
import url from "node:url";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const src = path.join(root, "src");
const dist = path.join(root, "dist");

const jsParts = [
  "00-core.js",
  "10-config.js",
  "20-theme.js",
  "30-preferences.js",
  "40-querystring.js",
  "50-api.js",
  "60-framework.js",
  "70-search-autocomplete.js",
  "80-shortcuts.js",
  "90-source-meta.js",
  "100-navbar.js",
  "110-dates.js",
  "120-table-sorting.js",
  "130-toast.js",
  "140-auto-apply-controls.js",
  "160-date-ranges.js",
  "170-taxonomy-pills.js",
];

const cssParts = [
  "00-theme-tokens.css",
  "10-base-layout-navbar.css",
  "20-components-tables-buttons.css",
  "30-evidence-media-print.css",
  "40-visualisations.css",
  "50-pdf-modal.css",
  "60-nav-preferences.css",
  "70-admin-and-forms.css",
  "80-tabs-tags-graphs.css",
  "90-taxonomy-and-utilities.css",
];

async function ensureDir(p) {
  await fs.mkdir(p, { recursive: true });
}

async function readPart(dir, rel) {
  return fs.readFile(path.join(dir, rel), "utf8");
}

async function bundleParts({ inputDir, parts, outputFile, banner }) {
  const chunks = [];
  for (const rel of parts) {
    chunks.push((await readPart(inputDir, rel)).trimEnd());
  }
  await fs.writeFile(outputFile, `${banner}\n\n${chunks.join("\n\n")}\n`, "utf8");
}

async function copyLooseRootFiles() {
  const entries = await fs.readdir(src, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    // app.js and styles.css are generated bundles now; any other root-level source
    // files can still be copied through for backwards compatibility.
    if (entry.name === "app.js" || entry.name === "styles.css") continue;
    await fs.copyFile(path.join(src, entry.name), path.join(dist, entry.name));
  }
}

async function main() {
  await ensureDir(dist);

  await bundleParts({
    inputDir: path.join(src, "js"),
    parts: jsParts,
    outputFile: path.join(dist, "app.js"),
    banner: "// Generated by scripts/build.mjs from src/js/*.js. Do not edit dist/app.js directly.",
  });

  await bundleParts({
    inputDir: path.join(src, "css"),
    parts: cssParts,
    outputFile: path.join(dist, "styles.css"),
    banner: "/* Generated by scripts/build.mjs from src/css/*.css. Do not edit dist/styles.css directly. */",
  });

  await copyLooseRootFiles();

  const stamp = new Date().toISOString();
  await fs.writeFile(path.join(dist, "BUILD_INFO.txt"), `Built: ${stamp}\n`, "utf8");
  console.log(`Bundled ${jsParts.length} JS part(s) and ${cssParts.length} CSS part(s) into dist/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
